"""Emit the resolved (non-secret) config the verbs source at runtime.

`engine/.hatch/resolved.env` is gitignored and machine-derived — never edited
by hand. The verbs source it (and `.env` for secrets) instead of branching on
the OS themselves.
"""
from pathlib import Path

from .resolve import Resolved

_HEADER = "# Generated by `hatch install` — do not edit. Derived from machines/<host>.toml + platform detection.\n"


def resolved_env_path(root: Path) -> Path:
    return root / "engine" / ".hatch" / "resolved.env"


def write_resolved_env(resolved: Resolved, out_path: Path) -> None:
    out_path.parent.mkdir(parents=True, exist_ok=True)
    body = "\n".join(f"{k}={v}" for k, v in resolved.env.items())
    out_path.write_text(_HEADER + body + "\n")


def link_env_for_units(out_path: Path, link: Path | None = None) -> Path:
    """Point `~/.config/hatch/env` at the emitted resolved.env.

    Install output rather than an artefact, which is why it lives here and not in a
    `provision.toml`: nothing in the repo is its source, and declaring one would have the
    manifest claim a generated file.

    A REAL FILE THERE IS REPLACED, unlike everywhere else in the provisioner. The refusal
    elsewhere protects a hand-placed config someone may still need; this path is ours, it is
    only ever a link to a file we generate, and leaving a stale copy would give the serving
    units a machine's old address with nothing to say so.
    """
    from .layout import UNITS_ENV_LINK
    link = link or UNITS_ENV_LINK
    link.parent.mkdir(parents=True, exist_ok=True)
    # A DIRECTORY THERE IS REFUSED, not unlinked. `unlink()` raises IsADirectoryError, which
    # is an uncaught exception that aborts the install before anything is deployed; every
    # other deploy target in the provisioner reports a blocked path and carries on.
    if link.is_dir() and not link.is_symlink():
        raise IsADirectoryError(f"{link} is a directory; the serving units need a file there")
    if link.is_symlink() or link.exists():
        link.unlink()
    link.symlink_to(out_path)
    return link


def read_resolved_env(path: Path) -> dict | None:
    """Parse an emitted resolved.env back, or None if it was never written.

    `doctor` checks this file rather than re-resolving, because this is the file
    the artefacts read: a machine toml edited without a re-install leaves the two
    disagreeing, and re-resolving would report the toml while the verb reads the
    stale value.
    """
    if not path.exists():
        return None
    env = {}
    for line in path.read_text().splitlines():
        line = line.strip()
        if line and not line.startswith("#") and "=" in line:
            key, _, val = line.partition("=")
            env[key.strip()] = val
    return env
